#server:
#  port: ${PORT:5005}


#keycloak:
#  realm: master
#  auth-server-url: http://localhost:8080/auth
#  ssl-required: external
#  resource: login-app  Client Id
#  credentials:
#    secret: 24007302-c88c-412c-9e16-5a5361283c54
#  use-resource-role-mappings: true
#  bearer-only: true
#  enable-basic-auth: true

