server:
  port: ${PORT:5010}

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI}

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: tag
          uri: http://blog-microservice-tag.herokuapp.com
          predicates:
            - Path=/tag/**
          filters:
            - name: Hystrix
              args:
                name: fallbackCommand
                fallbackUri: forward:/fallback/message

gateway:
  post:
    uri: https://blog-microservice-post.herokuapp.com
  tag:
    uri: http://blog-microservice-tag.herokuapp.com
  testimonial:
    uri: https://blog-microservice-post.herokuapp.com